# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20171022_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
    ]
